import { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, Check, ChevronRight, Compass, Heart, Home, Layers3, ListChecks, Ruler, ShieldCheck, Sparkles, Sprout, UserRound, Users, X } from 'lucide-react';
import { AssetSlot } from './assets/AssetSlot';
import { assetSlots, getAssetSlot } from './assets/registry';
import { demoMembers, demoTasks, categoryNames, statusNames, type Member, type Task } from './fixtures';
import { Button, Meter, PageHeading, Sheet } from './ui';

type Page = 'today' | 'tasks' | 'adventure' | 'hero' | 'family';
const pages = [{ id: 'today', title: 'Сегодня', icon: Home }, { id: 'tasks', title: 'Дела', icon: ListChecks }, { id: 'adventure', title: 'Мир', icon: Compass }, { id: 'hero', title: 'Герой', icon: UserRound }, { id: 'family', title: 'Семья', icon: Users }] as const;
type Overlay = { type: 'task'; task: Task } | { type: 'member'; member: Member } | { type: 'asset'; slotId: string } | { type: 'lab' } | { type: 'story' } | { type: 'map' } | { type: 'reward'; title: string; slotId: string } | null;
const categoryIcons = { home: Home, learning: BookOpen, care: Heart, together: Users };
const roleName = (member: Member) => member.familyRole === 'adult' ? 'Взрослый, игрок' : 'Ребёнок, игрок';
const membersForSize = (size: number) => size === 2 ? demoMembers.filter(member => member.id === 'alex' || member.id === 'sasha') : demoMembers.slice(0, size);

export function App() {
  const [page, setPage] = useState<Page>('today');
  const [actorId, setActorId] = useState('sasha');
  const [familySize, setFamilySize] = useState(4);
  const [inspect, setInspect] = useState(false);
  const [overlay, setOverlay] = useState<Overlay>(null);
  const [taskScope, setTaskScope] = useState('mine');
  const [taskStatus, setTaskStatus] = useState('all');
  const [heroSection, setHeroSection] = useState('look');
  const [bossPhase, setBossPhase] = useState(1);
  const members = membersForSize(familySize);
  const user = members.find(member => member.id === actorId) || members[0];
  const mine = demoTasks.filter(task => task.assignee === user.id);
  const nextTask = mine.find(task => task.status === 'ready') || demoTasks.find(task => task.assignee === 'family')!;
  const pending = demoTasks.filter(task => task.status === 'review' && members.some(member => member.id === task.assignee && member.familyRole === 'child'));
  const visibleTasks = (taskScope === 'review' ? pending : demoTasks.filter(task => taskScope === 'family' ? task.assignee === 'family' : task.assignee === user.id)).filter(task => taskScope === 'review' || taskStatus === 'all' || task.status === taskStatus);
  const emptyMine = taskScope === 'mine' && taskStatus === 'all';
  const go = (next: Page) => { setPage(next); setTaskScope('mine'); setTaskStatus('all'); window.scrollTo({ top: 0, behavior: 'instant' }); };
  const changeFamilySize = (size: number) => {
    const nextMembers = membersForSize(size);
    setFamilySize(size);
    if (!nextMembers.some(member => member.id === actorId)) {
      setActorId(nextMembers[0].id);
      setTaskScope('mine');
      setTaskStatus('all');
      setHeroSection('look');
    }
  };
  const slot = (id: string, label?: string, className?: string) => <AssetSlot slotId={id} label={label} className={className} inspect={inspect} onInspect={slotId => setOverlay({ type: 'asset', slotId })}/>;
  useEffect(() => { document.body.classList.add('v3-body'); return () => document.body.classList.remove('v3-body'); }, []);
  const selectedAsset = overlay?.type === 'asset' ? getAssetSlot(overlay.slotId) : undefined;
  function taskCard(task: Task, compact = false) {
    const Icon = categoryIcons[task.category]; const assignee = members.find(member => member.id === task.assignee);
    return <article className={`v3-task-card ${compact ? 'compact' : ''}`} key={task.id}><div className="v3-task-top"><span className={`v3-task-glyph ${task.category}`}><Icon size={22}/></span><div><p className="v3-caption">{task.assignee === 'family' ? 'Семейное дело' : `${categoryNames[task.category]} · ${assignee?.name || 'Участник'}`}</p><h3>{task.title}</h3></div><span className={`v3-status ${task.status}`}>{statusNames[task.status]}</span></div>{!compact && <p className="v3-task-copy">{task.description}</p>}<div className="v3-task-bottom"><span><ShieldCheck size={15}/>{task.requiresReview ? 'С подтверждением' : 'Самостоятельно'}</span><Button secondary={!compact} onClick={() => setOverlay({ type: 'task', task })}>{compact ? 'Посмотреть дело' : 'Подробнее'}<ArrowRight size={16}/></Button></div></article>;
  }
  const familyGrid = (limit?: number) => <div className="v3-members">{members.slice(0, limit).map(member => <div className="v3-member" key={member.id}>{slot('hero.portrait', member.name)}<button type="button" onClick={() => setOverlay({ type: 'member', member })} aria-label={`Посмотреть участника: ${member.name}`}><strong>{member.name}</strong><span>{member.familyRole === 'adult' ? 'Взрослый' : 'Ребёнок'}</span></button></div>)}</div>;
  return <div className="v3-app">
    <div className="v3-prototype-banner">Вариант 3 · этап 1 · демонстрационные данные</div>
    <header className="v3-topbar"><button type="button" className="v3-brand" onClick={() => go('today')} aria-label="Family Life, на главную"><span><Sprout size={25}/></span><strong>Family Life<small>Наше общее приключение</small></strong></button><label className="v3-profile"><span className="v3-sr">Тестовый профиль</span><select aria-label="Тестовый профиль" value={user.id} onChange={event => { setActorId(event.target.value); setTaskScope('mine'); setTaskStatus('all'); setHeroSection('look'); window.scrollTo({ top: 0, behavior: 'instant' }); }}>{members.map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label></header>
    <div className="v3-context-line"><span><UserRound size={14}/>{roleName(user)}</span><button type="button" onClick={() => setOverlay({ type: 'lab' })}><Ruler size={16}/>{inspect ? 'Разметка включена' : 'Разметка'}</button></div>
    {inspect && <div className="v3-inspector-note"><Layers3 size={18}/><span>Нажмите «Параметры» у нужного места, чтобы открыть размеры, слои и путь будущего файла.</span><button type="button" aria-label="Выключить разметку" onClick={() => setInspect(false)}><X size={18}/></button></div>}
    <main className="v3-main">
      {page === 'today' && <>
        <PageHeading title="Сегодня мы команда" text="Одно доброе дело меняет общий день."><span className="v3-date">Среда<br/>9 сентября</span></PageHeading>
        <section className="v3-home-scene">{slot('home.room', 'Здесь будет наш семейный дом')}<div className="v3-scene-caption"><span><Home size={16}/>Точка встречи семьи</span><button type="button" onClick={() => go('family')} aria-label="Открыть семейный круг"><Users size={15}/>{members.length}<ChevronRight size={16}/></button></div></section>
        <section className="v3-week-goal"><div><span className="v3-section-label">Наша неделя</span><strong>3 <small>из 8 общих шагов</small></strong></div><Meter value={3} max={8} label="Пример недельной цели"/><p>Двигаемся в своём темпе. Уже сделанное остаётся с нами.</p></section>
        <div className="v3-section-heading"><h2>Твоё ближайшее дело</h2><button type="button" className="v3-text-button" onClick={() => go('tasks')}>Все дела<ChevronRight size={16}/></button></div>{taskCard(nextTask, true)}
        {user.permissions.reviewChildTasks && <button type="button" className="v3-review-callout" onClick={() => { go('tasks'); setTaskScope('review'); }}><ShieldCheck size={23}/><span><strong>На проверке: {pending.length}</strong><small>{pending.length ? 'Посмотреть примеры результатов' : 'Очередь сейчас пуста'}</small></span><ChevronRight size={19}/></button>}
        <section className="v3-family-preview"><div className="v3-section-heading"><h2>Наш семейный круг</h2>{members.length > 4 && <button type="button" className="v3-text-button" onClick={() => go('family')}>Все {members.length}<ChevronRight size={16}/></button>}</div>{familyGrid(4)}</section>
        <div className="v3-quiet-note"><Heart size={19}/><p>Родители и дети играют вместе. Задачи помогают реальной жизни.</p></div>
      </>}
      {page === 'tasks' && <>
        <PageHeading title="Маленькие дела" text="Выбрать, сделать, поделиться результатом."/>
        <div className="v3-tabs" aria-label="Чьи дела">{[['mine', 'Мои'], ['family', 'Семейные'], ...(user.permissions.reviewChildTasks ? [['review', 'Проверить']] : [])].map(([id, label]) => <button type="button" key={id} aria-pressed={taskScope === id} onClick={() => setTaskScope(id)}>{label}{id === 'review' && <span>{pending.length}</span>}</button>)}</div>
        {taskScope !== 'review' && <label className="v3-filter">Состояние<select value={taskStatus} onChange={event => setTaskStatus(event.target.value)}><option value="all">Все дела</option><option value="ready">Впереди</option><option value="review">На проверке</option><option value="rework">На доработке</option><option value="done">Готово</option></select></label>}
        <div className="v3-task-list">{visibleTasks.map(task => taskCard(task))}</div>
        {!visibleTasks.length && <div className="v3-empty"><Check size={26}/><h2>Здесь спокойно</h2><p>{emptyMine ? 'Для этого профиля пока нет личных примеров. Посмотри общее дело семьи.' : 'В выбранном разделе нет примеров дел. Можно посмотреть другой статус.'}</p><Button secondary onClick={() => { setTaskScope(emptyMine ? 'family' : 'mine'); setTaskStatus('all'); }}>{emptyMine ? 'Посмотреть семейные дела' : 'Показать мои дела'}</Button></div>}
        <section className="v3-flow-note"><h2>Каждое старание заметно</h2><ol><li><span>1</span>Выполнить реальное дело</li><li><span>2</span>Поделиться результатом</li><li><span>3</span>Получить награду за принятый результат</li></ol><p>Проверяемое дело принимает взрослый. Доверенное дело принимается при отметке.</p></section>
      </>}
      {page === 'adventure' && <>
        <PageHeading title="За порогом дома" text="Наши дела становятся общей историей."/>
        <div className="v3-stage-label">Композиция приключения · механика на этапе 4</div>
        <section className="v3-adventure-card"><div className="v3-section-heading"><span className="v3-section-label">Первая экспедиция</span><span className="v3-caption">Глава 1</span></div><h2>Хранитель лесной тропы</h2>{slot('boss.main', `Босс · фаза ${bossPhase}`)}<div className="v3-boss-progress"><span>Пример состояния</span><strong>{[100, 55, 20][bossPhase - 1]}%</strong></div><Meter value={[100, 55, 20][bossPhase - 1]} max={100} label="Пример состояния босса"/>{inspect && <div className="v3-tabs" aria-label="Предпросмотр фазы босса">{[1, 2, 3].map(phase => <button type="button" key={phase} aria-pressed={phase === bossPhase} onClick={() => setBossPhase(phase)}>Фаза {phase}</button>)}</div>}<p>Прогресс приключения будет складываться из принятых результатов дел.</p><Button onClick={() => setOverlay({ type: 'story' })}>Как мы будем побеждать<ArrowRight size={17}/></Button></section>
        <button type="button" className="v3-route-card" onClick={() => setOverlay({ type: 'map' })}><Compass size={27}/><span><strong>Карта нашей истории</strong><small>Дом, тропа и первая встреча</small></span><ChevronRight size={20}/></button>
        <section className="v3-trophy-preview">{slot('family.trophy', 'Трофей за общую победу')}<div><h2>В истории семьи</h2><p>Завершённое приключение оставит память в доме.</p></div></section>
      </>}
      {page === 'hero' && <>
        <PageHeading title={`Герой: ${user.name}`} text="Личный путь в нашем общем приключении."/>
        <div className="v3-tabs" aria-label="Раздел героя">{[['look', 'Облик'], ['pet', 'Спутник'], ['collection', 'Коллекции']].map(([id, label]) => <button type="button" key={id} aria-pressed={heroSection === id} onClick={() => setHeroSection(id)}>{label}</button>)}</div>
        {heroSection === 'look' && <><section className="v3-hero-sheet"><div className="v3-hero-summary"><span><Sparkles size={16}/>Уровень {user.hero.level}</span><span>{user.hero.gold} золота</span></div>{slot(user.familyRole === 'adult' ? 'hero.adult' : 'hero.child', `Герой ${user.name}`)}<h2>{user.hero.title}</h2><div className="v3-hero-xp"><span>Опыт героя</span><strong>{user.hero.xp} / 100</strong></div><Meter value={user.hero.xp} max={100} label="Пример опыта героя"/></section><div className="v3-section-heading"><h2>Места для экипировки</h2><span className="v3-caption">Внешний вид</span></div><div className="v3-item-grid">{[['item.outfit', 'Куртка исследователя', 'Одежда'], ['item.weapon', 'Дорожный посох', 'Предмет в руке']].map(([id, title, category]) => <article key={id}>{slot(id, category)}<p className="v3-caption">{category}</p><h3>{title}</h3><Button secondary onClick={() => setOverlay({ type: 'reward', title, slotId: id })}>Посмотреть</Button></article>)}</div></>}
        {heroSection === 'pet' && <><section className="v3-pet-card"><span className="v3-section-label">Маленький спутник</span>{slot('pet.egg', 'Известное яйцо будущего питомца')}<h2>История начинается с заботы</h2><p>Вид питомца известен заранее. Срок роста проверим на этапе баланса.</p></section><section className="v3-pet-future">{slot('pet.companion', 'Будущий спутник')}<div><h2>Рядом с героем</h2><p>Здесь будет выросший питомец и его собственный уголок.</p></div></section></>}
        {heroSection === 'collection' && <><PageHeading title="Истории, которые остаются" text="Места для будущих наборов и семейных находок."/><section className="v3-collection-cover">{slot('collection.cover', 'Обложка коллекции')}<h2>Первая лесная коллекция</h2><p>Эскиз состава: одежда, предмет, спутник и находка для дома.</p></section><div className="v3-item-grid">{[['home.furniture', 'Находки для дома'], ['family.trophy', 'Семейные трофеи']].map(([id, title]) => <article key={id}>{slot(id, title)}<h3>{title}</h3><Button secondary onClick={() => setOverlay({ type: 'reward', title, slotId: id })}>Посмотреть</Button></article>)}</div><div className="v3-quiet-note"><BookOpen size={19}/><p>Цены, источники получения и права владения будут заданы отдельно от изображений.</p></div></>}
      </>}
      {page === 'family' && <>
        <PageHeading title="Наш семейный круг" text="У каждого свой герой. История — общая."/>
        <div className="v3-family-count"><Users size={21}/><strong>Участников в примере: {members.length}</strong><span>Все на своих местах</span></div>{familyGrid()}
        <section className="v3-family-goal"><div className="v3-section-heading"><h2>Один общий результат</h2><Sprout size={22}/></div><h3>Подготовить семейный вечер</h3><p>Небольшие посильные вклады каждого. Пропуск не стирает сделанное.</p><Meter value={3} max={8} label="Пример общей цели"/><span className="v3-caption">3 из 8 шагов в примере</span><Button secondary onClick={() => { go('tasks'); setTaskScope('family'); }}>Посмотреть общее дело<ArrowRight size={16}/></Button></section>
        {user.permissions.manageFamily && <section className="v3-parent-rights"><ShieldCheck size={23}/><div><h2>Игрок и взрослый</h2><p>Личный герой развивается за ваши дела. Проверка детских результатов и семейные покупки — отдельная ответственность.</p><Button secondary onClick={() => { go('tasks'); setTaskScope('review'); }}>Посмотреть результаты детей</Button></div></section>}
        <section className="v3-real-rewards"><Heart size={23}/><div><h2>Настоящие семейные награды</h2><p>Поход в парк, совместная игра, выбор фильма. Этот раздел сохранён в плане отдельно от виртуальных покупок.</p></div></section>
      </>}
    </main>
    <nav className="v3-nav" aria-label="Основная навигация">{pages.map(({ id, title, icon: Icon }) => <button type="button" key={id} aria-current={page === id ? 'page' : undefined} onClick={() => go(id)}><Icon size={22}/><span>{title}</span></button>)}</nav>
    {overlay?.type === 'task' && <Sheet title={overlay.task.title} close={() => setOverlay(null)}><span className={`v3-status ${overlay.task.status}`}>{statusNames[overlay.task.status]}</span><p>{overlay.task.description}</p><dl className="v3-details"><div><dt>Кому</dt><dd>{overlay.task.assignee === 'family' ? 'Участникам общего дела' : members.find(member => member.id === overlay.task.assignee)?.name}</dd></div><div><dt>Подтверждение</dt><dd>{overlay.task.requiresReview ? 'Взрослый принимает проверяемый результат' : 'Собственное дело взрослого — доверенная отметка, рабочая гипотеза'}</dd></div><div><dt>Результат</dt><dd>{overlay.task.rewardLabel}</dd></div></dl>{overlay.task.reworkReason && <section><h3>Что осталось сделать</h3><p>{overlay.task.reworkReason}</p><p>Это пример возврата на доработку. Уже выполненную часть не нужно начинать заново.</p></section>}{overlay.task.shares && <section><h3>Части общего дела</h3><p>Статичный пример личных вкладов. Каждая часть принимается отдельно; награды здесь не рассчитываются.</p><dl className="v3-details">{overlay.task.shares.filter(share => members.some(member => member.id === share.memberId)).map(share => <div key={share.memberId}><dt>{members.find(member => member.id === share.memberId)?.name}</dt><dd>{share.contribution}<br/><span className={`v3-status ${share.status}`}>{statusNames[share.status]}</span></dd></div>)}</dl></section>}<div className="v3-boundary-note">Сейчас открыт пример карточки. Правила согласуем на этапе 2. Реальную отправку, подтверждение и начисления подключим на этапе 3.</div><Button onClick={() => { const scope = overlay.task.assignee === 'family' ? 'family' : overlay.task.assignee === user.id ? 'mine' : 'review'; setOverlay(null); go('tasks'); setTaskScope(scope); }}>Вернуться к делам</Button></Sheet>}
    {overlay?.type === 'member' && <Sheet title={overlay.member.name} close={() => setOverlay(null)}>{slot(overlay.member.familyRole === 'adult' ? 'hero.adult' : 'hero.child', `Герой ${overlay.member.name}`, 'v3-modal-hero')}<h3>{overlay.member.hero.title}</h3><p>{roleName(overlay.member)}</p><p>Просмотр участника не меняет выбранный профиль. Взрослые и дети участвуют в игре; права управления выдаются отдельно.</p><Button secondary onClick={() => setOverlay(null)}>Вернуться к семье</Button></Sheet>}
    {overlay?.type === 'story' && <Sheet title="Каждое дело — вклад в историю" close={() => setOverlay(null)}><ol className="v3-explanation"><li>Выполняем реальные дела в удобном темпе.</li><li>Взрослый подтверждает проверяемые результаты детей.</li><li>Принятый результат двигает героя и приключение.</li><li>Общая победа остаётся в истории семьи.</li></ol><p>Босс не отнимает предметы за пропуски. Платёж не заменяет реальные дела.</p><div className="v3-boundary-note">Точные награды и длительность приключения проверяются в аудите баланса.</div><Button onClick={() => { setOverlay(null); go('tasks'); }}>Открыть дела</Button></Sheet>}
    {overlay?.type === 'map' && <Sheet title="Карта первой экспедиции" close={() => setOverlay(null)}>{slot('adventure.map', 'Карта приключения')}<ol className="v3-map-stops"><li><span/>Семейный дом</li><li><span/>Лесная тропа</li><li><span/>Встреча с хранителем</li></ol><p>Сейчас это маршрут для обсуждения. Изображение карты и механика открытий добавятся отдельно.</p><Button secondary onClick={() => setOverlay(null)}>Вернуться в мир</Button></Sheet>}
    {overlay?.type === 'reward' && <Sheet title={overlay.title} close={() => setOverlay(null)}>{slot(overlay.slotId, overlay.title)}<p>Идея для будущей коллекции. Изображение будет связано со своим определением предмета; цена и владение не хранятся в графическом файле.</p><div className="v3-boundary-note">В первом этапе покупок и выдачи предметов нет.</div><Button secondary onClick={() => setOverlay(null)}>Вернуться к герою</Button></Sheet>}
    {overlay?.type === 'lab' && <Sheet title="Проверка каркаса" close={() => setOverlay(null)}><p>Это инструменты просмотра третьего варианта. Здесь нет данных настоящей семьи.</p><label className="v3-switch"><input type="checkbox" checked={inspect} onChange={event => setInspect(event.target.checked)}/><span>Показывать контракт каждого места для графики</span></label><fieldset className="v3-fieldset"><legend>Размер тестовой семьи</legend><div className="v3-tabs">{[2, 4, 8].map(size => <button type="button" key={size} aria-pressed={familySize === size} onClick={() => changeFamilySize(size)}>Участников: {size}</button>)}</div><p>В минимальном примере — Алексей и Саша. Восемь участников — расширенный пример, а не лимит семьи.</p></fieldset><h3>Мест в реестре: {assetSlots.length}</h3><p>Ни одно место не загружает изображение. Экспортные размеры — кандидаты для будущей арт-проверки.</p><div className="v3-slot-index">{assetSlots.map(asset => <button type="button" key={asset.id} onClick={() => setOverlay({ type: 'asset', slotId: asset.id })}><span>{asset.label}<small>{asset.id}</small></span><ChevronRight size={17}/></button>)}</div><Button onClick={() => setOverlay(null)}>Вернуться к макету</Button></Sheet>}
    {overlay?.type === 'asset' && <Sheet title={selectedAsset?.label || 'Неизвестное место'} close={() => setOverlay(null)}>{selectedAsset ? <><code className="v3-slot-code">{selectedAsset.id}</code><p>{selectedAsset.description}</p><dl className="v3-details"><div><dt>Пропорции</dt><dd>{selectedAsset.aspectRatio}</dd></div><div><dt>Холст-кандидат</dt><dd>{selectedAsset.logicalCanvas.width} × {selectedAsset.logicalCanvas.height}</dd></div><div><dt>Экраны</dt><dd>{selectedAsset.screens.join(', ')}</dd></div><div><dt>Будущий путь</dt><dd><code>{selectedAsset.targetPath}</code></dd></div><div><dt>Точка привязки</dt><dd><code>{JSON.stringify(selectedAsset.anchor)}</code></dd></div><div><dt>Слои</dt><dd>{selectedAsset.layers.join(' → ')}</dd></div><div><dt>Состояния</dt><dd>{selectedAsset.states.join(', ')}</dd></div></dl><div className="v3-boundary-note">Файла пока нет, запрос по этому пути не выполняется. Порядок подготовки и вставки описан в ASSET_INSERTION_GUIDE.md.</div></> : <p>Для этого идентификатора нет записи. Чужое изображение не подставляется.</p>}<Button secondary onClick={() => setOverlay({ type: 'lab' })}>Ко всем местам</Button></Sheet>}
  </div>;
}
